id = "xquery"
name = "XQuery"
version = "0.0.1"
schema_version = 1
authors = ["Wolfgang Meier <wolfang@jinntec.de>"]
description = "XQuery extension with eXist-db linting"
repository = "https://github.com/wolfgangmm/zed-xquery"

[language_servers.xquery-lsp]
name = "XQuery Language Server"
languages = ["XQuery"]

[grammars.xquery]
repository = "https://github.com/wolfgangmm/tree-sitter-xquery"
rev = "dccd25fde9aca9adc42f1b8118c7184c6f2a932e"
